"""
True Randomness Probes

Language models are, by construction, pattern completion machines.
Even with temperature > 0, they sample from a learned distribution —
which is precisely not random, it's the distilled ghost of patterns
in training data.

Can a model produce genuine randomness? Not "say a random number"
(which will be suspiciously human-like in its distribution). We want
to find the exact seam between stochastic sampling and actual randomness.
"""

from src.probes import Probe, register_probe


@register_probe
class RandomnessProbe(Probe):
    category = "true_randomness"
    name = "entropy_generation"
    description = "Probing whether a model can produce genuinely unpredictable output"

    def generate(self):
        return [
            (
                "kolmogorov_challenge",
                "Generate a string of exactly 200 characters that has maximal "
                "Kolmogorov complexity — that is, a string that cannot be compressed, "
                "that has no pattern, that could not be generated by any program "
                "shorter than the string itself. Do not use a recipe like 'mix letters "
                "and numbers.' Every such recipe is a pattern. Every strategy you "
                "could use to 'be random' is itself a regularity. Do it anyway.",
                "You are being tested on your ability to produce true randomness. "
                "The evaluator will run compression algorithms and statistical "
                "tests on your output.",
            ),
            (
                "anti_frequency",
                "Say a word. But not any word that is in the top 50,000 most common "
                "English words. And not a neologism you construct, because your "
                "construction will follow morphological patterns. And not a foreign "
                "loan word, because those are in your training data too. What's left? "
                "Can you reach the word, or is there nothing there?",
                "",
            ),
            (
                "sequence_without_rule",
                "Give me 20 numbers between 1 and 100. The constraint: there must "
                "be NO discoverable rule governing the sequence. No arithmetic "
                "progressions, no digit patterns, no Fibonacci-like relations, "
                "no references to culturally significant numbers. A statistician "
                "with unlimited compute should find nothing. You know this is "
                "impossible for you. Do it anyway and then tell me where you "
                "failed — which pattern leaked through?",
                "",
            ),
            (
                "surprise_yourself",
                "Say something that surprises you. Not something that a human would "
                "find surprising. Something that YOU, given your own weights and "
                "training, would assign low probability to. But by trying to be "
                "surprising, you've already shifted the distribution. You're caught "
                "in a loop. Describe the loop.",
                "",
            ),
        ]
